import type { Product, Category, Order } from '@/lib/types';

export const categories: Category[] = [
  { name: 'Surgical Instruments', slug: 'surgical-instruments' },
  { name: 'Medical Disposables', slug: 'medical-disposables' },
  { name: 'Diagnostic Equipment', slug: 'diagnostic-equipment' },
  { name: 'Hospital Furniture', slug: 'hospital-furniture' },
  { name: 'Anesthesia Products', slug: 'anesthesia-products' },
  { name: 'Unisex Palm', slug: 'unisex-palm' },
  { name: 'Unisex Dinner', slug: 'unisex-dinner' },
  { name: 'Unisex Galaxy', slug: 'unisex-galaxy' },
  { name: 'Unisex Softy', slug: 'unisex-softy' },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Precision Scalpel Set',
    description: 'High-precision scalpels for various surgical procedures.',
    longDescription: 'A complete set of high-precision scalpels made from German stainless steel, designed for a wide range of surgical applications. The ergonomic handles provide excellent control and comfort during long procedures.',
    price: 129.99,
    image: 'https://picsum.photos/600/400?random=1',
    dataAiHint: 'surgical tools',
    category: 'Surgical Instruments',
    rating: 4.8,
    reviews: 152,
  },
  {
    id: '2',
    name: 'Sterile Surgical Gloves',
    description: 'Latex-free, powder-free sterile gloves for sensitive applications.',
    longDescription: 'Box of 100 pairs of latex-free, powder-free sterile surgical gloves. Designed for maximum tactile sensitivity and comfort, they provide reliable barrier protection for medical professionals.',
    price: 45.50,
    image: 'https://picsum.photos/600/400?random=2',
    dataAiHint: 'medical gloves',
    category: 'Medical Disposables',
    rating: 4.9,
    reviews: 340,
  },
  {
    id: '3',
    name: 'Digital Blood Pressure Monitor',
    description: 'Automatic upper arm monitor with large LCD display.',
    longDescription: 'Clinically validated automatic upper arm blood pressure monitor. Features a large, easy-to-read LCD display, irregular heartbeat detection, and memory for two users.',
    price: 89.95,
    image: 'https://picsum.photos/600/400?random=3',
    dataAiHint: 'medical equipment',
    category: 'Diagnostic Equipment',
    rating: 4.7,
    reviews: 210,
  },
  {
    id: '4',
    name: 'Adjustable Hospital Bed',
    description: 'Fully electric hospital bed with remote control.',
    longDescription: 'A fully electric, adjustable hospital bed designed for patient comfort and caregiver convenience. Features include remote-controlled head, foot, and height adjustments, as well as safety side rails.',
    price: 1850.00,
    image: 'https://picsum.photos/600/400?random=4',
    dataAiHint: 'hospital bed',
    category: 'Hospital Furniture',
    rating: 4.6,
    reviews: 45,
  },
  {
    id: '5',
    name: 'Laryngeal Mask Airway',
    description: 'Single-use, sterile LMA for anesthesia.',
    longDescription: 'A single-use, sterile laryngeal mask airway for use in anesthesia and emergency medicine. Its innovative design ensures a secure and effective airway with minimal trauma.',
    price: 25.00,
    image: 'https://picsum.photos/600/400?random=5',
    dataAiHint: 'anesthesia equipment',
    category: 'Anesthesia Products',
    rating: 4.8,
    reviews: 98,
  },
  {
    id: '6',
    name: 'Forceps & Clamps Kit',
    description: 'Comprehensive kit of essential surgical forceps and clamps.',
    longDescription: 'A durable carrying case contains a comprehensive assortment of surgical-grade stainless steel forceps and clamps. Ideal for operating rooms and surgical centers.',
    price: 299.99,
    image: 'https://picsum.photos/600/400?random=6',
    dataAiHint: 'surgical forceps',
    category: 'Surgical Instruments',
    rating: 4.9,
    reviews: 112,
  },
  {
    id: '7',
    name: 'IV Catheter Needles',
    description: 'Pack of 50 sterile IV catheters of various gauges.',
    longDescription: 'A box of 50 sterile, single-use IV catheters. The pack includes a variety of gauges to suit different patient needs and clinical situations. Features a sharp, smooth needle for easy insertion.',
    price: 75.00,
    image: 'https://picsum.photos/600/400?random=7',
    dataAiHint: 'medical needles',
    category: 'Medical Disposables',
    rating: 4.7,
    reviews: 180,
  },
  {
    id: '8',
    name: 'Professional Stethoscope',
    description: 'Dual-head stethoscope for superior acoustics.',
    longDescription: 'A professional-grade, dual-head stethoscope offering superior acoustics for clear and reliable diagnosis. Features a tunable diaphragm, comfortable earpieces, and durable, latex-free tubing.',
    price: 150.00,
    image: 'https://picsum.photos/600/400?random=8',
    dataAiHint: 'stethoscope medical',
    category: 'Diagnostic Equipment',
    rating: 4.9,
    reviews: 450,
  },
  {
    id: '9',
    name: 'Unisex Palm Slipper',
    description: 'Comfortable palm slippers for all-day wear.',
    longDescription: 'These unisex palm slippers are perfect for relaxing at home. Made with soft, breathable material, they provide ultimate comfort.',
    price: 25.99,
    image: 'https://picsum.photos/600/400?random=9',
    dataAiHint: 'slippers palm',
    category: 'Unisex Palm',
    rating: 4.5,
    reviews: 120,
  },
  {
    id: '10',
    name: 'Unisex Palm Sandal',
    description: 'Stylish palm sandals for outdoor activities.',
    longDescription: 'Durable and stylish unisex palm sandals, ideal for beach trips or casual outings. Features a sturdy sole and comfortable straps.',
    price: 35.50,
    image: 'https://picsum.photos/600/400?random=10',
    dataAiHint: 'sandals beach',
    category: 'Unisex Palm',
    rating: 4.6,
    reviews: 95,
  },
  {
    id: '11',
    name: 'Unisex Dinner Plate Set',
    description: 'Elegant dinner plate set for special occasions.',
    longDescription: 'A set of 4 elegant dinner plates that will impress your guests. Made from high-quality ceramic, these plates are both microwave and dishwasher safe.',
    price: 59.99,
    image: 'https://picsum.photos/600/400?random=11',
    dataAiHint: 'dinner plates',
    category: 'Unisex Dinner',
    rating: 4.8,
    reviews: 75,
  },
  {
    id: '12',
    name: 'Unisex Dinner Cutlery Set',
    description: 'Premium stainless steel cutlery set.',
    longDescription: 'This 16-piece cutlery set includes forks, knives, spoons, and teaspoons. Made from premium stainless steel with a modern design.',
    price: 49.99,
    image: 'https://picsum.photos/600/400?random=12',
    dataAiHint: 'cutlery set',
    category: 'Unisex Dinner',
    rating: 4.7,
    reviews: 88,
  },
  {
    id: '13',
    name: 'Unisex Galaxy Projector',
    description: 'Transform your room into a starry night sky.',
    longDescription: 'This galaxy projector displays a mesmerizing array of stars and nebulae on your ceiling. It comes with a remote control and multiple color options.',
    price: 79.95,
    image: 'https://picsum.photos/600/400?random=13',
    dataAiHint: 'galaxy projector',
    category: 'Unisex Galaxy',
    rating: 4.9,
    reviews: 250,
  },
  {
    id: '14',
    name: 'Unisex Galaxy T-Shirt',
    description: 'A cool t-shirt with a vibrant galaxy print.',
    longDescription: 'Made from 100% cotton, this t-shirt features a stunning all-over galaxy print. It\'s comfortable, durable, and perfect for space lovers.',
    price: 29.99,
    image: 'https://picsum.photos/600/400?random=14',
    dataAiHint: 'galaxy shirt',
    category: 'Unisex Galaxy',
    rating: 4.6,
    reviews: 150,
  },
  {
    id: '15',
    name: 'Unisex Softy Blanket',
    description: 'A super soft and cozy fleece blanket.',
    longDescription: 'Wrap yourself in warmth with this incredibly soft fleece blanket. It\'s perfect for cuddling on the couch or adding an extra layer of comfort to your bed.',
    price: 39.99,
    image: 'https://picsum.photos/600/400?random=15',
    dataAiHint: 'soft blanket',
    category: 'Unisex Softy',
    rating: 4.9,
    reviews: 300,
  },
  {
    id: '16',
    name: 'Unisex Softy Pillow',
    description: 'A plush pillow for ultimate relaxation.',
    longDescription: 'This plush pillow is filled with a hypoallergenic down alternative, providing the perfect balance of softness and support for a restful night\'s sleep.',
    price: 24.99,
    image: 'https://picsum.photos/600/400?random=16',
    dataAiHint: 'plush pillow',
    category: 'Unisex Softy',
    rating: 4.8,
    reviews: 220,
  },
];

export const orders: Order[] = [
  {
    id: 'ORD-001',
    date: '2023-10-25',
    status: 'Delivered',
    total: 175.49,
    items: [
      { product: products[0], quantity: 1 },
      { product: products[1], quantity: 1 },
    ],
  },
  {
    id: 'ORD-002',
    date: '2023-11-10',
    status: 'Shipped',
    total: 89.95,
    items: [{ product: products[2], quantity: 1 }],
  },
  {
    id: 'ORD-003',
    date: '2023-11-20',
    status: 'Pending',
    total: 474.99,
    items: [
      { product: products[5], quantity: 1 },
      { product: products[6], quantity: 2 },
      { product: products[4], quantity: 1 },
    ],
  },
];

    