import type { Product, Category, Order } from '@/lib/types';

export const categories: Category[] = [
  { name: 'Unisex Palm', slug: 'unisex-palm', image: 'https://picsum.photos/600/400?random=20', dataAiHint: 'palm leaves' },
  { name: 'Unisex Dinner', slug: 'unisex-dinner', image: 'https://picsum.photos/600/400?random=21', dataAiHint: 'dinner setting' },
  { name: 'Unisex Galaxy', slug: 'unisex-galaxy', image: 'https://picsum.photos/600/400?random=22', dataAiHint: 'galaxy stars' },
  { name: 'Unisex Softy', slug: 'unisex-softy', image: 'https://picsum.photos/600/400?random=23', dataAiHint: 'soft fabric' },
];

export const products: Product[] = [
  {
    id: '9',
    name: 'Unisex Palm Slipper',
    description: 'Comfortable palm slippers for all-day wear.',
    longDescription: 'These unisex palm slippers are perfect for relaxing at home. Made with soft, breathable material, they provide ultimate comfort.',
    price: 25.99,
    image: 'https://picsum.photos/600/400?random=9',
    dataAiHint: 'slippers palm',
    category: 'Unisex Palm',
    rating: 4.5,
    reviews: 120,
  },
  {
    id: '10',
    name: 'Unisex Palm Sandal',
    description: 'Stylish palm sandals for outdoor activities.',
    longDescription: 'Durable and stylish unisex palm sandals, ideal for beach trips or casual outings. Features a sturdy sole and comfortable straps.',
    price: 35.50,
    image: 'https://picsum.photos/600/400?random=10',
    dataAiHint: 'sandals beach',
    category: 'Unisex Palm',
    rating: 4.6,
    reviews: 95,
  },
  {
    id: '23',
    name: 'Unisex Palm Flip-Flops',
    description: 'Lightweight and durable palm flip-flops.',
    longDescription: 'The perfect companion for your summer adventures. These lightweight and durable flip-flops feature a cushioned footbed and a stylish palm-leaf pattern.',
    price: 19.99,
    image: 'https://picsum.photos/600/400?random=23',
    dataAiHint: 'beach flip-flops',
    category: 'Unisex Palm',
    rating: 4.4,
    reviews: 80,
  },
  {
    id: '24',
    name: 'Woven Palm Hat',
    description: 'A stylish hat made from woven palm leaves.',
    longDescription: 'Stay cool and shaded with this beautifully crafted hat made from natural woven palm leaves. Perfect for sunny days, it adds a touch of tropical elegance to any outfit.',
    price: 42.00,
    image: 'https://picsum.photos/600/400?random=24',
    dataAiHint: 'straw hat',
    category: 'Unisex Palm',
    rating: 4.7,
    reviews: 110,
  },
  {
    id: '25',
    name: 'Palm Leaf Tote Bag',
    description: 'A spacious and eco-friendly tote bag.',
    longDescription: 'Carry your essentials in style with this spacious and eco-friendly tote bag, featuring a chic palm leaf design. It\'s perfect for the beach, market, or everyday use.',
    price: 38.50,
    image: 'https://picsum.photos/600/400?random=25',
    dataAiHint: 'tote bag',
    category: 'Unisex Palm',
    rating: 4.8,
    reviews: 130,
  },
  {
    id: '26',
    name: 'Palm Accent Loafers',
    description: 'Comfortable loafers with a palm tree accent.',
    longDescription: 'These comfortable loafers are perfect for a casual yet sophisticated look. Made from high-quality materials, they feature a subtle embroidered palm tree accent.',
    price: 65.00,
    image: 'https://picsum.photos/600/400?random=26',
    dataAiHint: 'casual loafers',
    category: 'Unisex Palm',
    rating: 4.6,
    reviews: 90,
  },
  {
    id: '27',
    name: 'Tropical Espadrilles',
    description: 'Classic espadrilles with a tropical twist.',
    longDescription: 'Our classic espadrilles are given a tropical twist with a vibrant palm print. Lightweight and breathable, they are the perfect summer shoe for any occasion.',
    price: 48.00,
    image: 'https://picsum.photos/600/400?random=27',
    dataAiHint: 'summer shoes',
    category: 'Unisex Palm',
    rating: 4.5,
    reviews: 105,
  },
  {
    id: '28',
    name: 'Debossed Palm Wallet',
    description: 'A sleek wallet with a debossed palm design.',
    longDescription: 'This sleek and minimalist wallet is crafted from premium leather and features a subtle, debossed palm design. It has ample space for cards and cash.',
    price: 55.00,
    image: 'https://picsum.photos/600/400?random=28',
    dataAiHint: 'leather wallet',
    category: 'Unisex Palm',
    rating: 4.7,
    reviews: 150,
  },
  {
    id: '29',
    name: 'Palm Leaf Scarf',
    description: 'A lightweight scarf with a palm leaf print.',
    longDescription: 'Add a touch of tropical elegance to your look with this lightweight scarf. Made from a soft, breathable fabric, it features a beautiful all-over palm leaf print.',
    price: 22.50,
    image: 'https://picsum.photos/600/400?random=29',
    dataAiHint: 'lightweight scarf',
    category: 'Unisex Palm',
    rating: 4.6,
    reviews: 70,
  },
  {
    id: '11',
    name: 'Unisex Dinner Plate Set',
    description: 'Elegant dinner plate set for special occasions.',
    longDescription: 'A set of 4 elegant dinner plates that will impress your guests. Made from high-quality ceramic, these plates are both microwave and dishwasher safe.',
    price: 59.99,
    image: 'https://picsum.photos/600/400?random=11',
    dataAiHint: 'dinner plates',
    category: 'Unisex Dinner',
    rating: 4.8,
    reviews: 75,
  },
  {
    id: '12',
    name: 'Unisex Dinner Cutlery Set',
    description: 'Premium stainless steel cutlery set.',
    longDescription: 'This 16-piece cutlery set includes forks, knives, spoons, and teaspoons. Made from premium stainless steel with a modern design.',
    price: 49.99,
    image: 'https://picsum.photos/600/400?random=12',
    dataAiHint: 'cutlery set',
    category: 'Unisex Dinner',
    rating: 4.7,
    reviews: 88,
  },
  {
    id: '30',
    name: 'Crystal Wine Glasses',
    description: 'Set of 4 crystal wine glasses.',
    longDescription: 'Elevate your dining experience with this set of 4 premium crystal wine glasses. Their timeless design is perfect for any occasion, from casual dinners to formal gatherings.',
    price: 75.00,
    image: 'https://picsum.photos/600/400?random=30',
    dataAiHint: 'wine glasses',
    category: 'Unisex Dinner',
    rating: 4.8,
    reviews: 60,
  },
  {
    id: '31',
    name: 'Linen Tablecloth',
    description: 'A beautiful and durable tablecloth.',
    longDescription: 'This high-quality linen tablecloth adds a touch of elegance to any dining table. It\'s durable, easy to clean, and available in various sizes to fit your needs.',
    price: 89.99,
    image: 'https://picsum.photos/600/400?random=31',
    dataAiHint: 'linen tablecloth',
    category: 'Unisex Dinner',
    rating: 4.7,
    reviews: 55,
  },
  {
    id: '13',
    name: 'Unisex Galaxy Projector',
    description: 'Transform your room into a starry night sky.',
    longDescription: 'This galaxy projector displays a mesmerizing array of stars and nebulae on your ceiling. It comes with a remote control and multiple color options.',
    price: 79.95,
    image: 'https://picsum.photos/600/400?random=13',
    dataAiHint: 'galaxy projector',
    category: 'Unisex Galaxy',
    rating: 4.9,
    reviews: 250,
  },
  {
    id: '14',
    name: 'Unisex Galaxy T-Shirt',
    description: 'A cool t-shirt with a vibrant galaxy print.',
    longDescription: 'Made from 100% cotton, this t-shirt features a stunning all-over galaxy print. It\'s comfortable, durable, and perfect for space lovers.',
    price: 29.99,
    image: 'https://picsum.photos/600/400?random=14',
    dataAiHint: 'galaxy shirt',
    category: 'Unisex Galaxy',
    rating: 4.6,
    reviews: 150,
  },
  {
    id: '15',
    name: 'Unisex Softy Blanket',
    description: 'A super soft and cozy fleece blanket.',
    longDescription: 'Wrap yourself in warmth with this incredibly soft fleece blanket. It\'s perfect for cuddling on the couch or adding an extra layer of comfort to your bed.',
    price: 39.99,
    image: 'https://picsum.photos/600/400?random=15',
    dataAiHint: 'soft blanket',
    category: 'Unisex Softy',
    rating: 4.9,
    reviews: 300,
  },
  {
    id: '16',
    name: 'Unisex Softy Pillow',
    description: 'A plush pillow for ultimate relaxation.',
    longDescription: 'This plush pillow is filled with a hypoallergenic down alternative, providing the perfect balance of softness and support for a restful night\'s sleep.',
    price: 24.99,
    image: 'https://picsum.photos/600/400?random=16',
    dataAiHint: 'plush pillow',
    category: 'Unisex Softy',
    rating: 4.8,
    reviews: 220,
  },
];

export const orders: Order[] = [];
