import type { Product, Category, Order } from '@/lib/types';

export const categories: Category[] = [
  { name: 'Unisex Palm', slug: 'unisex-palm' },
  { name: 'Unisex Dinner', slug: 'unisex-dinner' },
  { name: 'Unisex Galaxy', slug: 'unisex-galaxy' },
  { name: 'Unisex Softy', slug: 'unisex-softy' },
];

export const products: Product[] = [
  {
    id: '9',
    name: 'Unisex Palm Slipper',
    description: 'Comfortable palm slippers for all-day wear.',
    longDescription: 'These unisex palm slippers are perfect for relaxing at home. Made with soft, breathable material, they provide ultimate comfort.',
    price: 25.99,
    image: 'https://picsum.photos/600/400?random=9',
    dataAiHint: 'slippers palm',
    category: 'Unisex Palm',
    rating: 4.5,
    reviews: 120,
  },
  {
    id: '10',
    name: 'Unisex Palm Sandal',
    description: 'Stylish palm sandals for outdoor activities.',
    longDescription: 'Durable and stylish unisex palm sandals, ideal for beach trips or casual outings. Features a sturdy sole and comfortable straps.',
    price: 35.50,
    image: 'https://picsum.photos/600/400?random=10',
    dataAiHint: 'sandals beach',
    category: 'Unisex Palm',
    rating: 4.6,
    reviews: 95,
  },
  {
    id: '11',
    name: 'Unisex Dinner Plate Set',
    description: 'Elegant dinner plate set for special occasions.',
    longDescription: 'A set of 4 elegant dinner plates that will impress your guests. Made from high-quality ceramic, these plates are both microwave and dishwasher safe.',
    price: 59.99,
    image: 'https://picsum.photos/600/400?random=11',
    dataAiHint: 'dinner plates',
    category: 'Unisex Dinner',
    rating: 4.8,
    reviews: 75,
  },
  {
    id: '12',
    name: 'Unisex Dinner Cutlery Set',
    description: 'Premium stainless steel cutlery set.',
    longDescription: 'This 16-piece cutlery set includes forks, knives, spoons, and teaspoons. Made from premium stainless steel with a modern design.',
    price: 49.99,
    image: 'https://picsum.photos/600/400?random=12',
    dataAiHint: 'cutlery set',
    category: 'Unisex Dinner',
    rating: 4.7,
    reviews: 88,
  },
  {
    id: '13',
    name: 'Unisex Galaxy Projector',
    description: 'Transform your room into a starry night sky.',
    longDescription: 'This galaxy projector displays a mesmerizing array of stars and nebulae on your ceiling. It comes with a remote control and multiple color options.',
    price: 79.95,
    image: 'https://picsum.photos/600/400?random=13',
    dataAiHint: 'galaxy projector',
    category: 'Unisex Galaxy',
    rating: 4.9,
    reviews: 250,
  },
  {
    id: '14',
    name: 'Unisex Galaxy T-Shirt',
    description: 'A cool t-shirt with a vibrant galaxy print.',
    longDescription: 'Made from 100% cotton, this t-shirt features a stunning all-over galaxy print. It\'s comfortable, durable, and perfect for space lovers.',
    price: 29.99,
    image: 'https://picsum.photos/600/400?random=14',
    dataAiHint: 'galaxy shirt',
    category: 'Unisex Galaxy',
    rating: 4.6,
    reviews: 150,
  },
  {
    id: '15',
    name: 'Unisex Softy Blanket',
    description: 'A super soft and cozy fleece blanket.',
    longDescription: 'Wrap yourself in warmth with this incredibly soft fleece blanket. It\'s perfect for cuddling on the couch or adding an extra layer of comfort to your bed.',
    price: 39.99,
    image: 'https://picsum.photos/600/400?random=15',
    dataAiHint: 'soft blanket',
    category: 'Unisex Softy',
    rating: 4.9,
    reviews: 300,
  },
  {
    id: '16',
    name: 'Unisex Softy Pillow',
    description: 'A plush pillow for ultimate relaxation.',
    longDescription: 'This plush pillow is filled with a hypoallergenic down alternative, providing the perfect balance of softness and support for a restful night\'s sleep.',
    price: 24.99,
    image: 'https://picsum.photos/600/400?random=16',
    dataAiHint: 'plush pillow',
    category: 'Unisex Softy',
    rating: 4.8,
    reviews: 220,
  },
];

export const orders: Order[] = [];
